//! ID generation strategy for INSERT column lists.
//!
//! Per Decision 0.2 of the embedded-writes design, embedded-mode writable
//! tables get `String DEFAULT generateUUIDv4()` on the ID column at DDL
//! time. When Cypher CREATE omits the ID property, we omit the column from
//! the INSERT and let chdb fill it.
//!
//! This module formalises the contract so other strategies (e.g.,
//! Snowflake) can plug in without changing the SQL generator. Phase 3 will
//! add an `id_generation: Option<IdStrategy>` field to `NodeSchema` and
//! wire `column_for_insert` into the INSERT builder.
//!
//! For Phase 2, this module is the contract; the only strategy actually
//! exercised by the renderer today is `Uuid` (the default), which produces
//! "omit the column from INSERT".

use serde::{Deserialize, Serialize};

use crate::render_plan::render_expr::RenderExpr;

/// How the ID column is filled when Cypher CREATE doesn't supply it.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum IdStrategy {
    /// DDL has `DEFAULT generateUUIDv4()`. Omit the column from INSERT.
    /// This is the default behaviour for embedded chdb writable tables.
    #[default]
    Uuid,
    /// User must supply the ID. Reject the INSERT if missing.
    Provided,
    /// Future: Snowflake-style ID generated by a SQL expression. Phase 3+.
    Snowflake,
}

/// Decision returned by `auto_id_decision`: when the user did NOT supply an
/// ID, what should the planner do for that column?
#[derive(Debug, Clone, PartialEq)]
pub enum IdInsertDecision {
    /// Don't auto-generate an ID expression — leave the column out of the
    /// INSERT and rely on the table's `DEFAULT` clause (e.g.,
    /// `generateUUIDv4()`) to fill it. The column is omitted from the
    /// INSERT, *not* dropped from any user-provided value.
    UseDdlDefault,
    /// Auto-generate an ID by emitting this expression in the INSERT
    /// column list. Used for strategies (e.g., Snowflake) that generate
    /// IDs via a SQL expression rather than a column DEFAULT.
    Generate(RenderExpr),
    /// The schema requires the user to supply the ID; abort the INSERT.
    RequireUserSupplied,
}

/// Compute what to do about the ID column when the user did **not** supply
/// it. Callers must short-circuit before calling this when the user *did*
/// supply the ID — the user value always wins regardless of strategy, and
/// this function does not encode that branch (it's a separate decision at
/// the call site).
pub fn auto_id_decision(strategy: IdStrategy) -> IdInsertDecision {
    match strategy {
        IdStrategy::Uuid => IdInsertDecision::UseDdlDefault,
        IdStrategy::Provided => IdInsertDecision::RequireUserSupplied,
        IdStrategy::Snowflake => IdInsertDecision::Generate(RenderExpr::Raw(
            // ClickHouse doesn't ship a built-in snowflake function; the
            // schema author wires one up via a UDF or a clickhouse-flavoured
            // expression. Pinning the call here is intentional — Phase 3
            // makes the call site overridable per schema.
            "generateSnowflakeID()".to_string(),
        )),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn uuid_uses_ddl_default() {
        assert_eq!(
            auto_id_decision(IdStrategy::Uuid),
            IdInsertDecision::UseDdlDefault
        );
    }

    #[test]
    fn provided_demands_user_id() {
        assert_eq!(
            auto_id_decision(IdStrategy::Provided),
            IdInsertDecision::RequireUserSupplied
        );
    }

    #[test]
    fn snowflake_emits_call() {
        match auto_id_decision(IdStrategy::Snowflake) {
            IdInsertDecision::Generate(RenderExpr::Raw(s)) => {
                assert!(s.contains("generateSnowflakeID"));
            }
            other => panic!("expected Generate(Raw(_)), got {:?}", other),
        }
    }
}
