//! ID generation strategy for INSERT column lists.
//!
//! Per Decision 0.2 of the embedded-writes design, embedded-mode writable
//! tables get `String DEFAULT generateUUIDv4()` on the ID column at DDL
//! time. When Cypher CREATE omits the ID property, we omit the column from
//! the INSERT and let chdb fill it.
//!
//! This module formalises the contract so other strategies (e.g.,
//! Snowflake) can plug in without changing the SQL generator. Phase 3 will
//! add an `id_generation: Option<IdStrategy>` field to `NodeSchema` and
//! wire `column_for_insert` into the INSERT builder.
//!
//! For Phase 2, this module is the contract; the only strategy actually
//! exercised by the renderer today is `Uuid` (the default), which produces
//! "omit the column from INSERT".

use serde::{Deserialize, Serialize};

use crate::render_plan::render_expr::RenderExpr;

/// How the ID column is filled when Cypher CREATE doesn't supply it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum IdStrategy {
    /// DDL has `DEFAULT generateUUIDv4()`. Omit the column from INSERT.
    /// This is the default behaviour for embedded chdb writable tables.
    Uuid,
    /// User must supply the ID. Reject the INSERT if missing.
    Provided,
    /// Future: Snowflake-style ID generated by a SQL expression. Phase 3+.
    Snowflake,
}

impl Default for IdStrategy {
    fn default() -> Self {
        IdStrategy::Uuid
    }
}

/// Decision returned by the strategy: should the renderer include the ID
/// column in the INSERT, and if so, what expression should it use?
#[derive(Debug, Clone, PartialEq)]
pub enum IdInsertDecision {
    /// Omit the column from the INSERT entirely. chdb will fill it via the
    /// column's `DEFAULT` expression.
    Omit,
    /// Include the column in the INSERT with this expression. Used for
    /// snowflake-style IDs that are generated by a function call rather
    /// than a column DEFAULT.
    Include(RenderExpr),
    /// User must supply the ID; abort the INSERT.
    RequireUserSupplied,
}

/// Compute the INSERT-list decision for a node ID column.
///
/// `user_supplied` is `true` when the user's CREATE clause included the ID
/// property explicitly (e.g., `CREATE (a:Person {id: 'foo', ...})`).
pub fn id_insert_decision(strategy: IdStrategy, user_supplied: bool) -> IdInsertDecision {
    if user_supplied {
        // User-provided IDs always win, regardless of strategy.
        return IdInsertDecision::Omit;
    }
    match strategy {
        IdStrategy::Uuid => IdInsertDecision::Omit,
        IdStrategy::Provided => IdInsertDecision::RequireUserSupplied,
        IdStrategy::Snowflake => IdInsertDecision::Include(RenderExpr::Raw(
            // ClickHouse doesn't ship a built-in snowflake function; the
            // schema author wires one up via a UDF or a clickhouse-flavoured
            // expression. Pinning the call here is intentional — Phase 3
            // makes the call site overridable per schema.
            "generateSnowflakeID()".to_string(),
        )),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn user_supplied_always_omits() {
        for s in [
            IdStrategy::Uuid,
            IdStrategy::Provided,
            IdStrategy::Snowflake,
        ] {
            assert_eq!(id_insert_decision(s, true), IdInsertDecision::Omit);
        }
    }

    #[test]
    fn uuid_default_omits() {
        assert_eq!(
            id_insert_decision(IdStrategy::Uuid, false),
            IdInsertDecision::Omit
        );
    }

    #[test]
    fn provided_demands_user_id() {
        assert_eq!(
            id_insert_decision(IdStrategy::Provided, false),
            IdInsertDecision::RequireUserSupplied
        );
    }

    #[test]
    fn snowflake_emits_call() {
        match id_insert_decision(IdStrategy::Snowflake, false) {
            IdInsertDecision::Include(RenderExpr::Raw(s)) => {
                assert!(s.contains("generateSnowflakeID"));
            }
            other => panic!("expected Include(Raw(_)), got {:?}", other),
        }
    }
}
