name: multi_relationship_test
version: "1.0"
description: "Test schema for multiple relationship types"

views:
  - name: test_graph
    nodes:
      User:
        source_table: users
        id_column: user_id
        label: User
        property_mappings:
          name: name

    relationships:
      FOLLOWS:
        source_table: follows
        from_column: from_user_id
        to_column: to_user_id
        type_name: FOLLOWS
        from_node_type: User
        to_node_type: User
        property_mappings: {}

      FRIENDS_WITH:
        source_table: friends
        from_column: from_user_id
        to_column: to_user_id
        type_name: FRIENDS_WITH
        from_node_type: User
        to_node_type: User
        property_mappings:
          since: friendship_date