name: social_network_demo
version: "1.0"
description: "Simple social network for ClickGraph demo"

views:
  - name: social_graph
    nodes:
      user:
        source_table: users
        id_column: user_id
        label: User
        property_mappings:
          name: full_name
          email: email_address
          
    relationships:
      follows:
        source_table: user_follows
        from_column: follower_id
        to_column: followed_id
        type_name: FOLLOWS
        from_node_type: User
        to_node_type: User
        property_mappings:
          since: follow_date