name: social_network_demo
version: "1.0"
description: "Simple social network for ClickGraph demo"

views:
  - name: social_graph
    nodes:
      User:
        source_table: users
        id_column: user_id  
        property_mappings:
          name: name
          age: age
          city: city
          
    relationships:
      FRIENDS_WITH:
        source_table: friendships
        from_column: user1_id
        to_column: user2_id
        from_node_type: User
        to_node_type: User
        property_mappings:
          since: since_date