name: social_benchmark
version: "1.0"
description: "Social network benchmark schema"

views:
  - name: social_graph
    nodes:
      User:
        source_table: users_bench
        id_column: user_id
        property_mappings:
          user_id: user_id
          full_name: full_name
          email_address: email_address
          registration_date: registration_date
          is_active: is_active
          country: country
          city: city
        label: User
    relationships:
      FOLLOWS:
        source_table: user_follows_bench
        from_column: follower_id
        to_column: followed_id
        type_name: FOLLOWS
        from_node_type: User
        to_node_type: User
        property_mappings:
          follow_date: follow_date
