//! Export functionality — write Cypher query results to files.
//!
//! Wraps generated SQL in `INSERT INTO FUNCTION file(...)` to leverage
//! ClickHouse's native file-writing capabilities via chdb.

use std::fmt;
use std::path::Path;

/// Supported export file formats.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExportFormat {
    Parquet,
    CSV,
    CSVWithNames,
    TSV,
    TSVWithNames,
    JSON,
    JSONEachRow,
}

impl ExportFormat {
    /// ClickHouse format name used in `file()` table function.
    pub fn clickhouse_name(&self) -> &'static str {
        match self {
            ExportFormat::Parquet => "Parquet",
            ExportFormat::CSV => "CSV",
            ExportFormat::CSVWithNames => "CSVWithNames",
            ExportFormat::TSV => "TabSeparated",
            ExportFormat::TSVWithNames => "TabSeparatedWithNames",
            ExportFormat::JSON => "JSON",
            ExportFormat::JSONEachRow => "JSONEachRow",
        }
    }
}

impl fmt::Display for ExportFormat {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.clickhouse_name())
    }
}

/// Options controlling how query results are exported.
#[derive(Debug, Clone, Default)]
pub struct ExportOptions {
    /// Output format. If `None`, auto-detected from the file extension.
    pub format: Option<ExportFormat>,
    /// Parquet compression codec (e.g. "snappy", "gzip", "lz4", "zstd").
    pub compression: Option<String>,
}

/// Detect the export format from a file extension.
///
/// Returns `None` for unrecognized extensions.
pub fn format_from_extension(path: &str) -> Option<ExportFormat> {
    let ext = Path::new(path)
        .extension()
        .and_then(|e| e.to_str())
        .map(|e| e.to_lowercase());

    match ext.as_deref() {
        Some("parquet" | "pq") => Some(ExportFormat::Parquet),
        Some("csv") => Some(ExportFormat::CSVWithNames),
        Some("tsv") => Some(ExportFormat::TSVWithNames),
        Some("json") => Some(ExportFormat::JSON),
        Some("ndjson" | "jsonl") => Some(ExportFormat::JSONEachRow),
        _ => None,
    }
}

/// Wrap a SELECT statement in `INSERT INTO FUNCTION file(...)`.
///
/// The `select_sql` should be a complete SELECT statement (as generated by
/// `cypher_to_sql`). The result is a single SQL string that chdb will execute,
/// writing the output directly to `output_path`.
pub fn build_export_sql(
    select_sql: &str,
    output_path: &str,
    options: &ExportOptions,
) -> Result<String, String> {
    let format = options
        .format
        .or_else(|| format_from_extension(output_path))
        .ok_or_else(|| {
            format!(
                "Cannot determine export format for '{}'. \
                 Specify format explicitly or use a recognized extension \
                 (.parquet, .csv, .tsv, .json, .ndjson, .jsonl).",
                output_path
            )
        })?;

    // Escape single quotes in the file path
    let escaped_path = output_path.replace('\'', "\\'");

    let mut sql = format!(
        "INSERT INTO FUNCTION file('{}', {})",
        escaped_path,
        format.clickhouse_name()
    );

    // Add SETTINGS for Parquet compression
    if let Some(ref codec) = options.compression {
        if format == ExportFormat::Parquet {
            sql.push_str(&format!(
                " SETTINGS output_format_parquet_compression_method = '{}'",
                codec
            ));
        }
    }

    sql.push(' ');
    sql.push_str(select_sql);

    Ok(sql)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_format_from_extension_parquet() {
        assert_eq!(
            format_from_extension("output.parquet"),
            Some(ExportFormat::Parquet)
        );
        assert_eq!(
            format_from_extension("data.pq"),
            Some(ExportFormat::Parquet)
        );
    }

    #[test]
    fn test_format_from_extension_csv() {
        assert_eq!(
            format_from_extension("results.csv"),
            Some(ExportFormat::CSVWithNames)
        );
    }

    #[test]
    fn test_format_from_extension_tsv() {
        assert_eq!(
            format_from_extension("results.tsv"),
            Some(ExportFormat::TSVWithNames)
        );
    }

    #[test]
    fn test_format_from_extension_json() {
        assert_eq!(
            format_from_extension("output.json"),
            Some(ExportFormat::JSON)
        );
        assert_eq!(
            format_from_extension("output.ndjson"),
            Some(ExportFormat::JSONEachRow)
        );
        assert_eq!(
            format_from_extension("output.jsonl"),
            Some(ExportFormat::JSONEachRow)
        );
    }

    #[test]
    fn test_format_from_extension_unknown() {
        assert_eq!(format_from_extension("output.txt"), None);
        assert_eq!(format_from_extension("noext"), None);
    }

    #[test]
    fn test_format_from_extension_case_insensitive() {
        assert_eq!(
            format_from_extension("data.PARQUET"),
            Some(ExportFormat::Parquet)
        );
        assert_eq!(
            format_from_extension("data.Csv"),
            Some(ExportFormat::CSVWithNames)
        );
    }

    #[test]
    fn test_build_export_sql_parquet() {
        let sql = build_export_sql(
            "SELECT full_name FROM test_db.users",
            "output.parquet",
            &ExportOptions::default(),
        )
        .unwrap();
        assert_eq!(
            sql,
            "INSERT INTO FUNCTION file('output.parquet', Parquet) SELECT full_name FROM test_db.users"
        );
    }

    #[test]
    fn test_build_export_sql_csv() {
        let sql =
            build_export_sql("SELECT * FROM t", "results.csv", &ExportOptions::default()).unwrap();
        assert_eq!(
            sql,
            "INSERT INTO FUNCTION file('results.csv', CSVWithNames) SELECT * FROM t"
        );
    }

    #[test]
    fn test_build_export_sql_explicit_format() {
        let opts = ExportOptions {
            format: Some(ExportFormat::JSONEachRow),
            ..Default::default()
        };
        let sql = build_export_sql("SELECT 1", "data.txt", &opts).unwrap();
        assert_eq!(
            sql,
            "INSERT INTO FUNCTION file('data.txt', JSONEachRow) SELECT 1"
        );
    }

    #[test]
    fn test_build_export_sql_parquet_compression() {
        let opts = ExportOptions {
            format: None,
            compression: Some("snappy".to_string()),
        };
        let sql = build_export_sql("SELECT 1", "out.parquet", &opts).unwrap();
        assert!(sql.contains("output_format_parquet_compression_method = 'snappy'"));
        assert!(sql.contains("INSERT INTO FUNCTION file('out.parquet', Parquet)"));
    }

    #[test]
    fn test_build_export_sql_compression_ignored_for_csv() {
        let opts = ExportOptions {
            format: None,
            compression: Some("gzip".to_string()),
        };
        let sql = build_export_sql("SELECT 1", "out.csv", &opts).unwrap();
        // Compression setting should NOT appear for CSV
        assert!(!sql.contains("compression"));
    }

    #[test]
    fn test_build_export_sql_unknown_extension_no_format() {
        let result = build_export_sql("SELECT 1", "output.xyz", &ExportOptions::default());
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .contains("Cannot determine export format"));
    }

    #[test]
    fn test_build_export_sql_path_with_quotes() {
        let sql = build_export_sql(
            "SELECT 1",
            "/tmp/it's a file.parquet",
            &ExportOptions::default(),
        )
        .unwrap();
        assert!(sql.contains("it\\'s a file.parquet"));
    }
}
