//! Python bindings for ClickGraph embedded graph query engine.
//!
//! Exposes `Database`, `Connection`, `QueryResult` to Python via PyO3.

use pyo3::exceptions::PyRuntimeError;
use pyo3::prelude::*;
use pyo3::types::{PyDict, PyList};

use clickgraph_embedded::database::{Database as RustDatabase, SystemConfig as RustSystemConfig};
use clickgraph_embedded::error::EmbeddedError;
use clickgraph_embedded::value::Value as RustValue;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn to_pyerr(e: EmbeddedError) -> PyErr {
    PyRuntimeError::new_err(e.to_string())
}

fn rust_value_to_py(py: Python<'_>, v: &RustValue) -> PyObject {
    match v {
        RustValue::Null => py.None(),
        RustValue::Bool(b) => b.into_pyobject(py).unwrap().to_owned().into_any().unbind(),
        RustValue::Int64(n) => n.into_pyobject(py).unwrap().into_any().unbind(),
        RustValue::Float64(f) => f.into_pyobject(py).unwrap().into_any().unbind(),
        RustValue::String(s) => s.into_pyobject(py).unwrap().into_any().unbind(),
        RustValue::List(items) => {
            let py_items: Vec<PyObject> = items.iter().map(|v| rust_value_to_py(py, v)).collect();
            PyList::new(py, &py_items).unwrap().into_any().unbind()
        }
        RustValue::Map(pairs) => {
            let dict = PyDict::new(py);
            for (k, v) in pairs {
                dict.set_item(k, rust_value_to_py(py, v)).unwrap();
            }
            dict.into_any().unbind()
        }
    }
}

// ---------------------------------------------------------------------------
// PyQueryResult — returned by Connection.query()
// ---------------------------------------------------------------------------

/// Result of a Cypher query. Iterable and indexable.
///
/// Rows can be accessed as dicts (default iteration) or tuples (Kuzu-compatible).
///
/// Dict-style (ClickGraph default):
///     for row in result:
///         print(row["u.name"])
///
/// Tuple-style (Kuzu-compatible):
///     while result.has_next():
///         row = result.get_next()   # returns a list of values
///         print(row[0])
#[pyclass(name = "QueryResult")]
struct PyQueryResult {
    column_names: Vec<String>,
    rows: Vec<Vec<RustValue>>,
    position: usize,
}

#[pymethods]
impl PyQueryResult {
    /// Column names in result order.
    ///
    /// Accessible as property ``result.column_names``. For Kuzu compatibility,
    /// also works with ``result.get_column_names()`` (auto-generated by PyO3).
    #[getter]
    fn column_names(&self) -> Vec<String> {
        self.column_names.clone()
    }

    /// Number of rows.
    #[getter]
    fn num_rows(&self) -> usize {
        self.rows.len()
    }

    /// Return True if there are more rows (Kuzu-compatible cursor).
    fn has_next(&self) -> bool {
        self.position < self.rows.len()
    }

    /// Return the next row as a list of values (Kuzu-compatible cursor).
    ///
    /// Returns a flat list in column order (like ``kuzu.FlatTuple``).
    fn get_next(&mut self, py: Python<'_>) -> PyResult<PyObject> {
        if self.position >= self.rows.len() {
            return Err(PyRuntimeError::new_err("No more rows"));
        }
        let row = &self.rows[self.position];
        self.position += 1;
        let py_vals: Vec<PyObject> = row.iter().map(|v| rust_value_to_py(py, v)).collect();
        Ok(PyList::new(py, &py_vals).unwrap().into_any().unbind())
    }

    /// Reset the cursor to the beginning.
    fn reset_iterator(&mut self) {
        self.position = 0;
    }

    /// Get all rows as a list of dicts.
    fn as_dicts(&self, py: Python<'_>) -> PyResult<PyObject> {
        let result = PyList::empty(py);
        for row in &self.rows {
            let dict = PyDict::new(py);
            for (i, col) in self.column_names.iter().enumerate() {
                let val = row
                    .get(i)
                    .map(|v| rust_value_to_py(py, v))
                    .unwrap_or_else(|| py.None());
                dict.set_item(col, val)?;
            }
            result.append(dict)?;
        }
        Ok(result.into_pyobject(py).unwrap().into_any().unbind())
    }

    /// Get a single row by index as a dict.
    fn get_row(&self, py: Python<'_>, index: usize) -> PyResult<PyObject> {
        if index >= self.rows.len() {
            return Err(PyRuntimeError::new_err(format!(
                "Row index {} out of range (0..{})",
                index,
                self.rows.len()
            )));
        }
        let dict = PyDict::new(py);
        for (i, col) in self.column_names.iter().enumerate() {
            let val = self.rows[index]
                .get(i)
                .map(|v| rust_value_to_py(py, v))
                .unwrap_or_else(|| py.None());
            dict.set_item(col, val)?;
        }
        Ok(dict.into_pyobject(py).unwrap().into_any().unbind())
    }

    fn __iter__(mut slf: PyRefMut<'_, Self>) -> PyRefMut<'_, Self> {
        slf.position = 0;
        slf
    }

    fn __next__(&mut self, py: Python<'_>) -> Option<PyObject> {
        if self.position >= self.rows.len() {
            return None;
        }
        let row = &self.rows[self.position];
        self.position += 1;

        let dict = PyDict::new(py);
        for (i, col) in self.column_names.iter().enumerate() {
            let val = row
                .get(i)
                .map(|v| rust_value_to_py(py, v))
                .unwrap_or_else(|| py.None());
            dict.set_item(col, val).ok();
        }
        Some(dict.into_pyobject(py).unwrap().into_any().unbind())
    }

    fn __len__(&self) -> usize {
        self.rows.len()
    }

    /// Access a row by index: ``result[0]`` returns a dict.
    fn __getitem__(&self, py: Python<'_>, index: isize) -> PyResult<PyObject> {
        let len = self.rows.len() as isize;
        let idx = if index < 0 { len + index } else { index };
        if idx < 0 || idx >= len {
            return Err(pyo3::exceptions::PyIndexError::new_err(format!(
                "row index {} out of range",
                index,
            )));
        }
        self.get_row(py, idx as usize)
    }

    fn __repr__(&self) -> String {
        format!(
            "<QueryResult columns={:?} rows={}>",
            self.column_names,
            self.rows.len()
        )
    }
}

// ---------------------------------------------------------------------------
// PyConnection — wraps Connection<'db>
// ---------------------------------------------------------------------------

/// A connection to an embedded ClickGraph database.
///
/// Create via ``Database.connect()`` or ``Connection(db)`` (Kuzu-compatible).
#[pyclass(name = "Connection")]
struct PyConnection {
    // We own the Database Arc so the connection can outlive Python's GC ordering.
    db: std::sync::Arc<RustDatabase>,
}

#[pymethods]
impl PyConnection {
    /// Kuzu-compatible constructor: ``conn = Connection(db)``.
    #[new]
    fn new(db: &PyDatabase) -> PyResult<Self> {
        Ok(PyConnection {
            db: std::sync::Arc::clone(&db.inner),
        })
    }

    /// Execute a Cypher query and return a QueryResult.
    ///
    /// >>> result = conn.query("MATCH (u:User) RETURN u.name LIMIT 5")
    /// >>> for row in result:
    /// ...     print(row["u.name"])
    #[pyo3(text_signature = "(self, cypher)")]
    fn query(&self, cypher: &str) -> PyResult<PyQueryResult> {
        // Create a Rust Connection with the underlying Database reference
        let conn = clickgraph_embedded::Connection::new(&self.db).map_err(to_pyerr)?;
        let result = conn.query(cypher).map_err(to_pyerr)?;

        let column_names = result.get_column_names().to_vec();
        let rows: Vec<Vec<RustValue>> = result.map(|row| row.values().to_vec()).collect();

        Ok(PyQueryResult {
            column_names,
            rows,
            position: 0,
        })
    }

    /// Alias for ``query()`` — Kuzu-compatible.
    ///
    /// >>> result = conn.execute("MATCH (u:User) RETURN u.name")
    #[pyo3(text_signature = "(self, cypher)")]
    fn execute(&self, cypher: &str) -> PyResult<PyQueryResult> {
        self.query(cypher)
    }

    /// Alias for ``query()`` — Neo4j driver-compatible.
    ///
    /// >>> result = conn.run("MATCH (u:User) RETURN u.name")
    #[pyo3(text_signature = "(self, cypher)")]
    fn run(&self, cypher: &str) -> PyResult<PyQueryResult> {
        self.query(cypher)
    }

    /// Translate Cypher to SQL without executing.
    ///
    /// Useful for debugging the generated ClickHouse SQL.
    #[pyo3(text_signature = "(self, cypher)")]
    fn query_to_sql(&self, cypher: &str) -> PyResult<String> {
        let conn = clickgraph_embedded::Connection::new(&self.db).map_err(to_pyerr)?;
        conn.query_to_sql(cypher).map_err(to_pyerr)
    }

    fn __repr__(&self) -> String {
        "<Connection>".to_string()
    }
}

// ---------------------------------------------------------------------------
// PyDatabase — wraps Database
// ---------------------------------------------------------------------------

/// An embedded ClickGraph database.
///
/// >>> db = Database("schema.yaml")
/// >>> conn = db.connect()
/// >>> result = conn.query("MATCH (u:User) RETURN u.name")
#[pyclass(name = "Database")]
struct PyDatabase {
    inner: std::sync::Arc<RustDatabase>,
}

#[pymethods]
impl PyDatabase {
    /// Open a database from a YAML schema file.
    ///
    /// Args:
    ///     schema_path: Path to the YAML graph schema.
    ///     session_dir: Optional directory for chdb session data.
    ///     data_dir: Optional base directory for relative source: paths.
    ///     max_threads: Optional maximum threads for chdb.
    ///     s3_access_key_id: AWS access key for S3 sources.
    ///     s3_secret_access_key: AWS secret key for S3 sources.
    ///     s3_region: AWS region for S3 sources.
    ///     s3_endpoint_url: Custom S3 endpoint URL.
    ///     gcs_access_key_id: GCS HMAC access key.
    ///     gcs_secret_access_key: GCS HMAC secret.
    ///     azure_storage_account_name: Azure storage account name.
    ///     azure_storage_account_key: Azure storage account key.
    ///     azure_storage_connection_string: Azure Blob Storage connection string.
    #[new]
    #[pyo3(signature = (
        schema_path,
        *,
        session_dir = None,
        data_dir = None,
        max_threads = None,
        s3_access_key_id = None,
        s3_secret_access_key = None,
        s3_region = None,
        s3_endpoint_url = None,
        s3_session_token = None,
        gcs_access_key_id = None,
        gcs_secret_access_key = None,
        azure_storage_account_name = None,
        azure_storage_account_key = None,
        azure_storage_connection_string = None,
    ))]
    #[allow(clippy::too_many_arguments)]
    fn new(
        schema_path: &str,
        session_dir: Option<String>,
        data_dir: Option<String>,
        max_threads: Option<usize>,
        s3_access_key_id: Option<String>,
        s3_secret_access_key: Option<String>,
        s3_region: Option<String>,
        s3_endpoint_url: Option<String>,
        s3_session_token: Option<String>,
        gcs_access_key_id: Option<String>,
        gcs_secret_access_key: Option<String>,
        azure_storage_account_name: Option<String>,
        azure_storage_account_key: Option<String>,
        azure_storage_connection_string: Option<String>,
    ) -> PyResult<Self> {
        let credentials = clickgraph_embedded::StorageCredentials {
            s3_access_key_id,
            s3_secret_access_key,
            s3_region,
            s3_endpoint_url,
            s3_session_token,
            gcs_access_key_id,
            gcs_secret_access_key,
            azure_storage_account_name,
            azure_storage_account_key,
            azure_storage_connection_string,
        };

        let config = RustSystemConfig {
            session_dir: session_dir.map(std::path::PathBuf::from),
            data_dir: data_dir.map(std::path::PathBuf::from),
            max_threads,
            credentials,
        };

        let db = RustDatabase::new(schema_path, config).map_err(to_pyerr)?;
        Ok(PyDatabase {
            inner: std::sync::Arc::new(db),
        })
    }

    /// Create a connection to this database.
    fn connect(&self) -> PyResult<PyConnection> {
        Ok(PyConnection {
            db: std::sync::Arc::clone(&self.inner),
        })
    }

    /// Shorthand: execute a query directly (creates a temporary connection).
    #[pyo3(text_signature = "(self, cypher)")]
    fn execute(&self, cypher: &str) -> PyResult<PyQueryResult> {
        let conn = self.connect()?;
        conn.query(cypher)
    }

    fn __repr__(&self) -> String {
        "<Database>".to_string()
    }
}

// ---------------------------------------------------------------------------
// Module
// ---------------------------------------------------------------------------

/// ClickGraph — embedded graph query engine.
///
/// Run Cypher queries over Parquet, Iceberg, Delta Lake and S3 data
/// without a ClickHouse server.
///
/// Quick start:
///
/// >>> import clickgraph
/// >>> db = clickgraph.Database("schema.yaml")
/// >>> conn = db.connect()
/// >>> for row in conn.query("MATCH (u:User) RETURN u.name LIMIT 5"):
/// ...     print(row["u.name"])
#[pymodule]
fn _clickgraph(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<PyDatabase>()?;
    m.add_class::<PyConnection>()?;
    m.add_class::<PyQueryResult>()?;
    Ok(())
}
