

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureFree(
				UniffiForeignFutureFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureStructU8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureStructU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureStructI8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureStructI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureStructU16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureStructU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureStructI16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureStructI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureStructU32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureStructU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureStructI32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureStructI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureStructU64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureStructU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureStructI64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureStructI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureStructF32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureStructF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureStructF64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureStructF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void* returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t callback_data, UniffiForeignFutureStructPointer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompletePointer(
				UniffiForeignFutureCompletePointer cb, uint64_t callback_data, UniffiForeignFutureStructPointer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureStructRustBuffer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureStructRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureStructVoid result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureStructVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_CLONE_CONNECTION
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_CLONE_CONNECTION
void* uniffi_clickgraph_ffi_fn_clone_connection(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_FREE_CONNECTION
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_FREE_CONNECTION
void uniffi_clickgraph_ffi_fn_free_connection(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_CREATE_EDGE
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_CREATE_EDGE
void uniffi_clickgraph_ffi_fn_method_connection_create_edge(void* ptr, RustBuffer edge_type, RustBuffer from_id, RustBuffer to_id, RustBuffer properties, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_CREATE_EDGES
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_CREATE_EDGES
void uniffi_clickgraph_ffi_fn_method_connection_create_edges(void* ptr, RustBuffer edge_type, RustBuffer batch, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_CREATE_NODE
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_CREATE_NODE
RustBuffer uniffi_clickgraph_ffi_fn_method_connection_create_node(void* ptr, RustBuffer label, RustBuffer properties, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_CREATE_NODES
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_CREATE_NODES
RustBuffer uniffi_clickgraph_ffi_fn_method_connection_create_nodes(void* ptr, RustBuffer label, RustBuffer batch, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_DELETE_EDGES
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_DELETE_EDGES
void uniffi_clickgraph_ffi_fn_method_connection_delete_edges(void* ptr, RustBuffer edge_type, RustBuffer filter, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_DELETE_NODES
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_DELETE_NODES
void uniffi_clickgraph_ffi_fn_method_connection_delete_nodes(void* ptr, RustBuffer label, RustBuffer filter, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_EXECUTE_SQL
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_EXECUTE_SQL
void uniffi_clickgraph_ffi_fn_method_connection_execute_sql(void* ptr, RustBuffer sql, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_EXPORT
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_EXPORT
void uniffi_clickgraph_ffi_fn_method_connection_export(void* ptr, RustBuffer cypher, RustBuffer output_path, RustBuffer options, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_EXPORT_TO_SQL
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_EXPORT_TO_SQL
RustBuffer uniffi_clickgraph_ffi_fn_method_connection_export_to_sql(void* ptr, RustBuffer cypher, RustBuffer output_path, RustBuffer options, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_IMPORT_JSON
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_IMPORT_JSON
void uniffi_clickgraph_ffi_fn_method_connection_import_json(void* ptr, RustBuffer label, RustBuffer json_lines, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_IMPORT_JSON_FILE
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_IMPORT_JSON_FILE
void uniffi_clickgraph_ffi_fn_method_connection_import_json_file(void* ptr, RustBuffer label, RustBuffer file_path, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_QUERY
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_QUERY
void* uniffi_clickgraph_ffi_fn_method_connection_query(void* ptr, RustBuffer cypher, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_QUERY_GRAPH
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_QUERY_GRAPH
void* uniffi_clickgraph_ffi_fn_method_connection_query_graph(void* ptr, RustBuffer cypher, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_QUERY_REMOTE
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_QUERY_REMOTE
void* uniffi_clickgraph_ffi_fn_method_connection_query_remote(void* ptr, RustBuffer cypher, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_QUERY_REMOTE_GRAPH
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_QUERY_REMOTE_GRAPH
void* uniffi_clickgraph_ffi_fn_method_connection_query_remote_graph(void* ptr, RustBuffer cypher, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_QUERY_TO_SQL
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_QUERY_TO_SQL
RustBuffer uniffi_clickgraph_ffi_fn_method_connection_query_to_sql(void* ptr, RustBuffer cypher, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_STORE_SUBGRAPH
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_STORE_SUBGRAPH
RustBuffer uniffi_clickgraph_ffi_fn_method_connection_store_subgraph(void* ptr, void* graph, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_UPSERT_EDGE
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_UPSERT_EDGE
void uniffi_clickgraph_ffi_fn_method_connection_upsert_edge(void* ptr, RustBuffer edge_type, RustBuffer from_id, RustBuffer to_id, RustBuffer properties, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_UPSERT_NODE
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_CONNECTION_UPSERT_NODE
RustBuffer uniffi_clickgraph_ffi_fn_method_connection_upsert_node(void* ptr, RustBuffer label, RustBuffer properties, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_CLONE_DATABASE
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_CLONE_DATABASE
void* uniffi_clickgraph_ffi_fn_clone_database(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_FREE_DATABASE
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_FREE_DATABASE
void uniffi_clickgraph_ffi_fn_free_database(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_CONSTRUCTOR_DATABASE_OPEN
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_CONSTRUCTOR_DATABASE_OPEN
void* uniffi_clickgraph_ffi_fn_constructor_database_open(RustBuffer schema_path, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_CONSTRUCTOR_DATABASE_OPEN_SQL_ONLY
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_CONSTRUCTOR_DATABASE_OPEN_SQL_ONLY
void* uniffi_clickgraph_ffi_fn_constructor_database_open_sql_only(RustBuffer schema_path, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_CONSTRUCTOR_DATABASE_OPEN_WITH_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_CONSTRUCTOR_DATABASE_OPEN_WITH_CONFIG
void* uniffi_clickgraph_ffi_fn_constructor_database_open_with_config(RustBuffer schema_path, RustBuffer config, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_DATABASE_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_DATABASE_CONNECT
void* uniffi_clickgraph_ffi_fn_method_database_connect(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_CLONE_GRAPHRESULT
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_CLONE_GRAPHRESULT
void* uniffi_clickgraph_ffi_fn_clone_graphresult(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_FREE_GRAPHRESULT
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_FREE_GRAPHRESULT
void uniffi_clickgraph_ffi_fn_free_graphresult(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_GRAPHRESULT_EDGE_COUNT
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_GRAPHRESULT_EDGE_COUNT
uint64_t uniffi_clickgraph_ffi_fn_method_graphresult_edge_count(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_GRAPHRESULT_EDGES
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_GRAPHRESULT_EDGES
RustBuffer uniffi_clickgraph_ffi_fn_method_graphresult_edges(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_GRAPHRESULT_NODE_COUNT
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_GRAPHRESULT_NODE_COUNT
uint64_t uniffi_clickgraph_ffi_fn_method_graphresult_node_count(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_GRAPHRESULT_NODES
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_GRAPHRESULT_NODES
RustBuffer uniffi_clickgraph_ffi_fn_method_graphresult_nodes(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_CLONE_QUERYRESULT
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_CLONE_QUERYRESULT
void* uniffi_clickgraph_ffi_fn_clone_queryresult(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_FREE_QUERYRESULT
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_FREE_QUERYRESULT
void uniffi_clickgraph_ffi_fn_free_queryresult(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_QUERYRESULT_COLUMN_NAMES
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_QUERYRESULT_COLUMN_NAMES
RustBuffer uniffi_clickgraph_ffi_fn_method_queryresult_column_names(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_QUERYRESULT_GET_ALL_ROWS
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_QUERYRESULT_GET_ALL_ROWS
RustBuffer uniffi_clickgraph_ffi_fn_method_queryresult_get_all_rows(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_QUERYRESULT_GET_NEXT
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_QUERYRESULT_GET_NEXT
RustBuffer uniffi_clickgraph_ffi_fn_method_queryresult_get_next(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_QUERYRESULT_HAS_NEXT
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_QUERYRESULT_HAS_NEXT
int8_t uniffi_clickgraph_ffi_fn_method_queryresult_has_next(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_QUERYRESULT_NUM_ROWS
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_QUERYRESULT_NUM_ROWS
uint64_t uniffi_clickgraph_ffi_fn_method_queryresult_num_rows(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_QUERYRESULT_RESET
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_FN_METHOD_QUERYRESULT_RESET
void uniffi_clickgraph_ffi_fn_method_queryresult_reset(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_clickgraph_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_clickgraph_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUSTBUFFER_FREE
void ffi_clickgraph_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_clickgraph_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_U8
void ffi_clickgraph_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_U8
void ffi_clickgraph_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_U8
void ffi_clickgraph_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_clickgraph_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_I8
void ffi_clickgraph_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_I8
void ffi_clickgraph_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_I8
void ffi_clickgraph_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_clickgraph_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_U16
void ffi_clickgraph_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_U16
void ffi_clickgraph_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_U16
void ffi_clickgraph_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_clickgraph_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_I16
void ffi_clickgraph_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_I16
void ffi_clickgraph_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_I16
void ffi_clickgraph_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_clickgraph_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_U32
void ffi_clickgraph_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_U32
void ffi_clickgraph_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_U32
void ffi_clickgraph_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_clickgraph_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_I32
void ffi_clickgraph_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_I32
void ffi_clickgraph_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_I32
void ffi_clickgraph_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_clickgraph_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_U64
void ffi_clickgraph_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_U64
void ffi_clickgraph_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_U64
void ffi_clickgraph_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_clickgraph_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_I64
void ffi_clickgraph_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_I64
void ffi_clickgraph_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_I64
void ffi_clickgraph_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_clickgraph_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_F32
void ffi_clickgraph_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_F32
void ffi_clickgraph_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_F32
void ffi_clickgraph_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_clickgraph_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_F64
void ffi_clickgraph_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_F64
void ffi_clickgraph_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_F64
void ffi_clickgraph_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_clickgraph_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_POINTER
void ffi_clickgraph_ffi_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_POINTER
void ffi_clickgraph_ffi_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_POINTER
void ffi_clickgraph_ffi_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_POINTER
void* ffi_clickgraph_ffi_rust_future_complete_pointer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_clickgraph_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_clickgraph_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_clickgraph_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_clickgraph_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_POLL_VOID
void ffi_clickgraph_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_clickgraph_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_FREE_VOID
void ffi_clickgraph_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_clickgraph_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_CREATE_EDGE
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_CREATE_EDGE
uint16_t uniffi_clickgraph_ffi_checksum_method_connection_create_edge(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_CREATE_EDGES
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_CREATE_EDGES
uint16_t uniffi_clickgraph_ffi_checksum_method_connection_create_edges(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_CREATE_NODE
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_CREATE_NODE
uint16_t uniffi_clickgraph_ffi_checksum_method_connection_create_node(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_CREATE_NODES
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_CREATE_NODES
uint16_t uniffi_clickgraph_ffi_checksum_method_connection_create_nodes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_DELETE_EDGES
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_DELETE_EDGES
uint16_t uniffi_clickgraph_ffi_checksum_method_connection_delete_edges(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_DELETE_NODES
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_DELETE_NODES
uint16_t uniffi_clickgraph_ffi_checksum_method_connection_delete_nodes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_EXECUTE_SQL
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_EXECUTE_SQL
uint16_t uniffi_clickgraph_ffi_checksum_method_connection_execute_sql(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_EXPORT
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_EXPORT
uint16_t uniffi_clickgraph_ffi_checksum_method_connection_export(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_EXPORT_TO_SQL
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_EXPORT_TO_SQL
uint16_t uniffi_clickgraph_ffi_checksum_method_connection_export_to_sql(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_IMPORT_JSON
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_IMPORT_JSON
uint16_t uniffi_clickgraph_ffi_checksum_method_connection_import_json(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_IMPORT_JSON_FILE
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_IMPORT_JSON_FILE
uint16_t uniffi_clickgraph_ffi_checksum_method_connection_import_json_file(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_QUERY
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_QUERY
uint16_t uniffi_clickgraph_ffi_checksum_method_connection_query(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_QUERY_GRAPH
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_QUERY_GRAPH
uint16_t uniffi_clickgraph_ffi_checksum_method_connection_query_graph(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_QUERY_REMOTE
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_QUERY_REMOTE
uint16_t uniffi_clickgraph_ffi_checksum_method_connection_query_remote(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_QUERY_REMOTE_GRAPH
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_QUERY_REMOTE_GRAPH
uint16_t uniffi_clickgraph_ffi_checksum_method_connection_query_remote_graph(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_QUERY_TO_SQL
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_QUERY_TO_SQL
uint16_t uniffi_clickgraph_ffi_checksum_method_connection_query_to_sql(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_STORE_SUBGRAPH
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_STORE_SUBGRAPH
uint16_t uniffi_clickgraph_ffi_checksum_method_connection_store_subgraph(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_UPSERT_EDGE
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_UPSERT_EDGE
uint16_t uniffi_clickgraph_ffi_checksum_method_connection_upsert_edge(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_UPSERT_NODE
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_CONNECTION_UPSERT_NODE
uint16_t uniffi_clickgraph_ffi_checksum_method_connection_upsert_node(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_DATABASE_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_DATABASE_CONNECT
uint16_t uniffi_clickgraph_ffi_checksum_method_database_connect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_GRAPHRESULT_EDGE_COUNT
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_GRAPHRESULT_EDGE_COUNT
uint16_t uniffi_clickgraph_ffi_checksum_method_graphresult_edge_count(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_GRAPHRESULT_EDGES
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_GRAPHRESULT_EDGES
uint16_t uniffi_clickgraph_ffi_checksum_method_graphresult_edges(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_GRAPHRESULT_NODE_COUNT
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_GRAPHRESULT_NODE_COUNT
uint16_t uniffi_clickgraph_ffi_checksum_method_graphresult_node_count(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_GRAPHRESULT_NODES
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_GRAPHRESULT_NODES
uint16_t uniffi_clickgraph_ffi_checksum_method_graphresult_nodes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_QUERYRESULT_COLUMN_NAMES
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_QUERYRESULT_COLUMN_NAMES
uint16_t uniffi_clickgraph_ffi_checksum_method_queryresult_column_names(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_QUERYRESULT_GET_ALL_ROWS
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_QUERYRESULT_GET_ALL_ROWS
uint16_t uniffi_clickgraph_ffi_checksum_method_queryresult_get_all_rows(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_QUERYRESULT_GET_NEXT
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_QUERYRESULT_GET_NEXT
uint16_t uniffi_clickgraph_ffi_checksum_method_queryresult_get_next(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_QUERYRESULT_HAS_NEXT
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_QUERYRESULT_HAS_NEXT
uint16_t uniffi_clickgraph_ffi_checksum_method_queryresult_has_next(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_QUERYRESULT_NUM_ROWS
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_QUERYRESULT_NUM_ROWS
uint16_t uniffi_clickgraph_ffi_checksum_method_queryresult_num_rows(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_QUERYRESULT_RESET
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_METHOD_QUERYRESULT_RESET
uint16_t uniffi_clickgraph_ffi_checksum_method_queryresult_reset(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_CONSTRUCTOR_DATABASE_OPEN
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_CONSTRUCTOR_DATABASE_OPEN
uint16_t uniffi_clickgraph_ffi_checksum_constructor_database_open(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_CONSTRUCTOR_DATABASE_OPEN_SQL_ONLY
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_CONSTRUCTOR_DATABASE_OPEN_SQL_ONLY
uint16_t uniffi_clickgraph_ffi_checksum_constructor_database_open_sql_only(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_CONSTRUCTOR_DATABASE_OPEN_WITH_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_CLICKGRAPH_FFI_CHECKSUM_CONSTRUCTOR_DATABASE_OPEN_WITH_CONFIG
uint16_t uniffi_clickgraph_ffi_checksum_constructor_database_open_with_config(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_CLICKGRAPH_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_clickgraph_ffi_uniffi_contract_version(void
    
);
#endif

