name: ecommerce_graph
version: "1.0"
views:
  - name: ecommerce_view
    nodes:
      Customer:
        source_table: "customers"
        id_column: "customer_id"
        label: "Customer"
        property_mappings:
          name: "CONCAT(first_name, ' ', last_name)"
          email: "email"
          age: "age" 
          gender: "gender"
          country: "country"
          city: "city"
          registration_date: "registration_date"
          total_spent: "total_spent"
          is_premium: "is_premium"
          customer_id: "customer_id"

      Product:
        source_table: "products"
        id_column: "product_id"
        label: "Product"
        property_mappings:
          name: "name"
          category: "category"
          brand: "brand"
          price: "price"
          rating: "rating"
          num_reviews: "num_reviews"
          in_stock: "in_stock"
          created_date: "created_date"
          product_id: "product_id"

    relationships:
      PURCHASED:
        source_table: "orders"
        from_column: "customer_id"
        to_column: "product_id"
        type_name: "PURCHASED"
        property_mappings:
          order_id: "order_id"
          quantity: "quantity"
          unit_price: "unit_price"
          total_amount: "total_amount"
          order_date: "order_date"
          order_time: "order_time"
          status: "status"