name: social_network_view
version: "1.0"
views:
  - name: user_interaction_graph
    nodes:
      # Map users table to graph nodes
      - label: user
        database: social
        table: users
        node_id: user_id
        property_mappings:
          name: full_name
          email: email_address
          created_at: registration_date
        label: User
        filter_condition: "is_active = 1"
      
      # Map posts table to content nodes
      - label: post
        database: social
        table: posts
        node_id: post_id
        property_mappings:
          title: post_title
          content: post_content
          created_at: post_date
        label: Post
    
    edges:
      # Map follows table to FOLLOWS relationships
      - type: follows
        database: social
        table: user_follows
        from_id: follower_id
        to_id: followed_id
        property_mappings:
          since: follow_date
        type_name: FOLLOWS
      
      # Map post authorship to AUTHORED relationships
      - type: authored
        database: social
        table: posts
        from_id: author_id
        to_id: post_id
        property_mappings:
          created_at: post_date
        type_name: AUTHORED
      
      # Map likes to LIKED relationships
      - type: likes
        database: social
        table: post_likes
        from_id: user_id
        to_id: post_id
        property_mappings:
          created_at: like_date
        type_name: LIKED

  - name: product_interaction_graph
    nodes:
      # Map products table to product nodes
      - label: product
        database: ecommerce
        table: products
        node_id: product_id
        property_mappings:
          name: product_name
          price: current_price
          category: product_category
        label: Product
      
      # Reuse users table for customer nodes
      - label: customer
        database: ecommerce
        table: users
        node_id: user_id
        property_mappings:
          name: full_name
          region: country_code
        label: Customer
        filter_condition: "has_purchased = 1"
    
    edges:
      # Map purchases to PURCHASED relationships
      - type: purchased
        database: ecommerce
        table: orders
        from_id: user_id
        to_id: product_id
        property_mappings:
          date: order_date
          quantity: order_quantity
          price: unit_price
        type_name: PURCHASED