name: social_network_view
version: "1.0"
views:
  - name: user_interaction_graph
    nodes:
      # Map users table to graph nodes
      user:
        source_table: users
        node_id: user_id
        property_mappings:
          name: full_name
          email: email_address
          created_at: registration_date
        label: User
        filter_condition: "is_active = 1"
      
      # Map posts table to content nodes
      post:
        source_table: posts
        node_id: post_id
        property_mappings:
          title: post_title
          content: post_content
          created_at: post_date
        label: Post
    
    relationships:
      # Map follows table to FOLLOWS relationships
      follows:
        source_table: user_follows
        from_id: follower_id
        to_id: followed_id
        property_mappings:
          since: follow_date
        type_name: FOLLOWS
      
      # Map post authorship to AUTHORED relationships
      authored:
        source_table: posts
        from_id: author_id
        to_id: post_id
        property_mappings:
          created_at: post_date
        type_name: AUTHORED
      
      # Map likes to LIKED relationships
      likes:
        source_table: post_likes
        from_id: user_id
        to_id: post_id
        property_mappings:
          created_at: like_date
        type_name: LIKED

  - name: product_interaction_graph
    nodes:
      # Map products table to product nodes
      product:
        source_table: products
        node_id: product_id
        property_mappings:
          name: product_name
          price: current_price
          category: product_category
        label: Product
      
      # Reuse users table for customer nodes
      customer:
        source_table: users
        node_id: user_id
        property_mappings:
          name: full_name
          region: country_code
        label: Customer
        filter_condition: "has_purchased = 1"
    
    relationships:
      # Map purchases to PURCHASED relationships
      purchased:
        source_table: orders
        from_id: user_id
        to_id: product_id
        property_mappings:
          date: order_date
          quantity: order_quantity
          price: unit_price
        type_name: PURCHASED